### ISSUE TITLE
Installation Difficulties

### ISSUE THREAD

**Issue by knu2xs** [mnfost/ArcGIS_Tweets#1]
When trying to replicate and use your work, installation on an ArcGIS 10.3.1 box is somewhat difficult. While I can get the packages you suggested installed, I still encounter an error when attempting to access your Python Toolbox. Yes, I have also manually installed SciPy as well to hopefully alleviate the issue. While this appears an issue with `sys.path`, I am hoping you may be able to help since you obviously got this working and likely know how to resolve the issues. Obviously I am using a default installation of Python with ArcGIS, a normal pattern. Please advise if there are additional steps I am missing.

```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Python27\ArcGIS10.3\lib\site-packages\scipy\stats\__init__.py", line 321, in <module>
    from .stats import *
  File "C:\Python27\ArcGIS10.3\lib\site-packages\scipy\stats\stats.py", line 180, in <module>
    import scipy.special as special
  File "C:\Python27\ArcGIS10.3\lib\site-packages\scipy\special\__init__.py", line 601, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by mnfost** [comment]
Hi Joel, thanks for reaching out.

This error can indicate a number of issues with SciPy installation, but most likely the error is occurring because you installed 32-bit Python but 64-bit libraries or vice versa. 

Try going through some of these links to find recommendations on how to resolve your issue.
- [Google Results for Error](https://www.google.com/webhp?sourceid=chrome-instant&rlz=1C5CHFA_enUS578US579&ion=1&espv=2&es_th=1&ie=UTF-8#q=ImportError:+DLL+load+failed:+The+specified+module+could+not+be+found+scipy)
- [SciPy Specific Solution 1](https://stackoverflow.com/questions/22753695/dll-load-failed-with-scipy-optimize)
- [SciPy Specific Solution 2](https://stackoverflow.com/questions/17480779/importerror-when-importing-certain-modules-from-scipy)
- [More General Solution 1](https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found)
- [More General Solution 2](https://stackoverflow.com/questions/32671918/windows-importerror-dll-load-failed-the-specified-module-could-not-be-found)
- [More General Solution 3](https://stackoverflow.com/questions/22221427/importerror-dll-load-failed-the-specified-procedure-could-not-be-found-python)
- [More General Solution 4](https://gis.stackexchange.com/questions/121157/how-to-fix-python-importerror-dll-load-failed-the-specified-module-could-not-b)

I hope these help. 
Please let me know if you are still having problems after trying some of these recommendations.
